# Generated by Django 5.2.4 on 2025-07-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_history', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='growthhistory',
            options={'ordering': ['-data_hora_evento'], 'verbose_name': 'Histórico de Crescimento', 'verbose_name_plural': 'Históricos de Crescimento'},
        ),
        migrations.AddField(
            model_name='growthhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_histories', to=settings.AUTH_USER_MODEL),
        ),
    ]
