# Generated by Django 5.2.4 on 2025-07-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estagio', models.CharField(help_text='Ex: Germinação, Vegetativo, Floração', max_length=100)),
                ('duracao_em_dias', models.PositiveIntegerField()),
                ('luz_diaria_em_horas', models.PositiveSmallIntegerField()),
                ('ppfd', models.PositiveIntegerField(help_text='Photosynthetic Photon Flux Density')),
                ('umidade_recomendada', models.CharField(help_text='Ex: 50%-60%', max_length=20)),
                ('temperatura_recomendada', models.CharField(help_text='Ex: 20°C-25°C', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
