# Generated by Django 5.2.4 on 2025-07-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='user',
        ),
    ]
