# Generated by Django 5.2.4 on 2025-07-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0002_remove_stage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='tipo_estagio',
            field=models.CharField(help_text='Ex: Germinação, Vegetativo, Floração', max_length=100, unique=True),
        ),
    ]
