# Generated by Django 5.2.4 on 2025-07-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_alter_stage_tipo_estagio'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagio_atual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transicao_de', to='stage.stage', verbose_name='Do Estágio')),
                ('proximo_estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicao_para', to='stage.stage', verbose_name='Para o Estágio')),
            ],
            options={
                'verbose_name': 'Transição de Estágio',
                'verbose_name_plural': 'Transições de Estágio',
                'constraints': [models.UniqueConstraint(fields=('estagio_atual', 'proximo_estagio'), name='transicao_unica')],
            },
        ),
    ]
