# Generated by Django 5.2.4 on 2025-07-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fertilizer', '0001_initial'),
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('DIARIA', 'Todos os dias'), ('ALTERNADA', 'Dia sim, dia não'), ('INTERVALO', 'A cada X dias')], max_length=20, verbose_name='Frequência')),
                ('dias_intervalo', models.PositiveSmallIntegerField(blank=True, help_text="Preencha apenas se a frequência for 'A cada X dias'.", null=True, verbose_name='Intervalo em dias')),
                ('quantidade_agua_ml', models.PositiveIntegerField(verbose_name='Quantidade de Água (ml)')),
                ('horario_preferencial', models.TimeField(default='08:00', verbose_name='Horário do Alerta')),
                ('ultima_rega_registrada', models.DateField(blank=True, help_text='Deixe em branco para começar hoje. Será atualizado automaticamente.', null=True, verbose_name='Data da Última Rega')),
                ('is_active', models.BooleanField(default=True, verbose_name='Agendamento Ativo')),
                ('fertilizantes', models.ManyToManyField(blank=True, to='fertilizer.fertilizer', verbose_name='Fertilizantes (opcional)')),
                ('planta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watering_schedule', to='plants.plant', verbose_name='Planta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento de Rega',
                'verbose_name_plural': 'Agendamentos de Rega',
                'ordering': ['planta__nome'],
            },
        ),
    ]
