# Generated by Django 5.2.4 on 2025-07-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('assunto', models.CharField(max_length=200)),
                ('corpo_html', models.TextField()),
                ('corpo_texto', models.TextField(help_text='Versão em texto puro do e-mail.')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada')], default='PENDENTE', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='email_marketing.emailtemplate')),
            ],
        ),
    ]
