# Generated by Django 5.2.4 on 2025-07-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment', '0001_initial'),
        ('stage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('identificacao', models.CharField(help_text='Um ID único para a planta. Ex: SK-01', max_length=50)),
                ('data_plantio', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(default='Ativa', max_length=50)),
                ('ambiente_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='environment.environment')),
                ('estagio_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stage.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'identificacao')},
            },
        ),
    ]
