# Generated by Django 5.2.4 on 2025-07-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_ambiente_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='data_ultima_mudanca_estagio',
            field=models.DateField(blank=True, help_text='Data da última transição de estágio. Preenchido automaticamente.', null=True),
        ),
    ]
