# Generated by Django 5.2.4 on 2025-07-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_data_ultima_mudanca_estagio'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='especie',
            field=models.CharField(blank=True, help_text='Ex: Sativa, Indica, Híbrida, Tomate Cereja, etc.', max_length=100),
        ),
    ]
