# Generated by Django 5.2.4 on 2025-07-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='strain',
            field=models.CharField(blank=True, help_text='Ex: Skunk #1, Runtz, Coração de Boi, etc.', max_length=100, verbose_name='Variedade/Strain'),
        ),
    ]
