# Generated by Django 5.2.4 on 2025-07-12 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('area', models.DecimalField(decimal_places=2, help_text='Em m²', max_digits=5)),
                ('numero_maximo_plantas', models.PositiveIntegerField()),
                ('estagio_preparado', models.ForeignKey(blank=True, help_text='Selecione se o ambiente é otimizado para um estágio específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stage.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
